### ISSUE TITLE
OSPF Configuration Example / Supported?

### ISSUE THREAD

**Issue by cutty201** [eloicaso/bird-openwrt#1]
UPDATE! 

So I looked in the  bird4-openwrt / src / config directory and saw a sample config that clearly had sections for configuring OSPF. When I tried to port in my configuration I noticed that the OSPF section of the /tmp/bird4.conf was missing. Eventually I just copy and pasted, exactly, the ospf sections from the sample config and still it does not get translated into the /tmp/bird4.conf. 

I just started looking through  bird4-openwrt / src / model / gen_proto.lua and I did not see anything that defines the OSPF section. IS it in fact not implemented? 
## -MAtt 

I just compiled the package and am going to start playing with it. I use BIRD for OSPF and was wondering whether this package supported that configuration, as there are no references in the documentation. 

I am assuming areas are set similarly to the BGP Templates. Thanks again .

-MAtt

**Comment by eloicaso** [comment]
Hi MAtt!

First of all, sorry for the delay answering your question. As you already said, OSPF is in development but I have been really busy so it isn't totally finished, so currently is not supported. I am working on it again, and I want to make it supported and usable really soon.

Just to clarify it, Bird already supports 100% OSPF so, if you are using this integration, you will not find the "user-friendly" interface that is already done for BGP, but Bird is completely functional using their own tutorials.

Regards,

**Comment by cutty201** [comment]
It looks like you've added more ospf stuff :) I've now switched to BGP
