### ISSUE TITLE
BGP Filters Out of Order, does not add export statement

### ISSUE THREAD

**Issue by cutty201** [eloicaso/bird-openwrt#2]
When adding a BGP Filter using UCI it orders the filter configuration AFTER the BGP protocol configuration which causes Bird to fail with the following error: 

```
bird: /tmp/bird4.conf, line 36: No such filter.
```

and the relevant configuration is as follows: 

```
config filter 'out_cisco1'
    option type 'bgp'
    option instance 'beta'
    option file_path '/var/filters/cisco_out1'
config bgp beta
    option description 'Description of the BGP instance'
    option neighbor_address '51.220.0.1'
    option neighbor_as '300'
    option local_address '51.220.0.2'
    option local_as '200'
    option import 'all'
```

The resulting config file outputs as: 

```
protocol bgp beta {
    local as 200;
    import all;
    export filter out_cisco1;
    neighbor 51.220.0.1 as 300;
}

filter out_cisco1 {
    if (net = 51.220.0.0/24) then
    {
        bgp_community.add((300,445));
        accept;
    }
    else reject;
}
```

the `filter out_cisco1 {...}` is the contents of `/var/filters/cisco_out1`

Was hoping you could point out what I am doing wrong. I was looking through the code, but I don't really know LUA to figure out if I could make the bug fix. 

-Matt

**Comment by eloicaso** [comment]
Closing. This will be fixed on v0.3 soon.
